# -*- coding: utf-8 -*-
"""pendeteksi-wajah.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aA6CYkbsjK3xiU5r0asqm9hIwqQmF_Xc
"""

# Willi
# Pendeteksi Wajah Menggunakan Gambar

# Import library yang dibutuhkan.
import cv2
from google.colab.patches import cv2_imshow
import matplotlib.pyplot as plt

image = cv2.imread('sample_data/teteh-nike-ardilla.jpg')
cv2_imshow(image)

image_gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)
cv2_imshow(image_gray)

cascade_classifier = cv2.CascadeClassifier(f"{cv2.data.haarcascades}haarcascade_smile.xml")
# cascade_classifier = cv2.CascadeClassifier(f"{cv2.data.haarcascades}haarcascade_fullbody.xml")

detected_objects = cascade_classifier.detectMultiScale(image_gray)
detected_objects

image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
warna = (0, 255, 0)
if len(detected_objects) != 0:
  for (x, y, width, height) in detected_objects:
    cv2.rectangle(image_rgb, (x, y), (x + height, y + width), warna, 2)

cv2_imshow(image_rgb)